version: "3.8"

services:
  go-mod:
    image: golang:1.17.5-alpine3.15
    volumes:
      - ./src:/go/src/github.com/hyorimitsu/hello-cloud-profiler/src
    working_dir: /go/src/github.com/hyorimitsu/hello-cloud-profiler/src
    command: go mod vendor
