version: "2.4"

services: 
    api:
        image: golang:1.14.2-alpine3.11
        ports: 
            - 8081:8081
        environment:
            - PORT=8081
        volumes: 
            - ../src:/go/src/github.com/hyorimitsu/gcp-cloudprofiler-go-sample/src
        working_dir: /go/src/github.com/hyorimitsu/gcp-cloudprofiler-go-sample/src
        restart: always
        container_name: api
        command: go run main.go --host 0.0.0.0 --port 8081
