runtime: go114
#env: standard  # MEMO: https://cloud.google.com/appengine/docs/the-appengine-environments

env_variables:
  SERVICE_NAME: "sample-profile"
  SERVICE_VERSION: "1.0.1"

#instance_class: F1
#automatic_scaling:
#  target_cpu_utilization: 0.6
#  target_throughput_utilization: 0.6
#  min_instances: 1
#  max_instances: 5
#  min_idle_instances: 1
#  max_idle_instances: automatic
#  min_pending_latency: automatic
#  max_pending_latency: automatic
#  max_concurrent_requests: 80

handlers:
  - url: /.*
    script: auto